import re

HEADER = """`timescale 1ns/1ps
// AUTO-GENERATED by pipeline.py
module fifo_props_gen #(parameter int WIDTH = 8, parameter int DEPTH = 8) (
  input logic clk, rst_n, wr_en, rd_en,
  input logic [WIDTH-1:0] wdata, rdata,
  input logic full, empty,
  input logic [$clog2(DEPTH):0] count
);"""

ALLOWED = {"$past", "$rose", "$fell", "$stable", "$changed",
           "$countones", "$onehot", "$onehot0", "$clog2"}
BAD = re.compile(r"[;`\"\\]|##|\b(always|bind|assert|assume|property|sequence|module|initial|final)\b")


def sanitize_name(n):
    return re.sub(r"\W", "_", str(n).lower()).strip("_")[:40] or "p"


def validate(p):
    """Return an error string, or None if the candidate is safe to compile."""
    for k in ("name", "operator", "consequent"):
        if not str(p.get(k, "")).strip():
            return f"missing {k}"
    if p["operator"] not in ("|->", "|=>", "invariant"):
        return "bad operator"
    if p["operator"] != "invariant" and not str(p.get("antecedent", "")).strip():
        return "missing antecedent"
    for f in ("antecedent", "consequent"):
        s = str(p.get(f, ""))
        if BAD.search(s):
            return f"forbidden token in {f}"
        for fn in re.findall(r"\$\w+", s):
            if fn not in ALLOWED:
                return f"system function {fn} not allowed"
        if s.count("(") != s.count(")"):
            return f"unbalanced parentheses in {f}"
    return None


def render_module(cands):
    """Return (sv_text, {name: (first_line, last_line)}) for error attribution."""
    lines, ranges = HEADER.splitlines(), {}
    for p in cands:
        n = p["name"]
        start = len(lines) + 1
        desc = re.sub(r"\s+", " ", str(p.get("description", "")))
        ant = str(p.get("antecedent", "")).strip() or "1'b1"
        cons = str(p["consequent"]).strip()
        body = cons if p["operator"] == "invariant" else f"({ant}) {p['operator']} ({cons})"
        lines += [
            f"  // {desc}",
            f"  int cov_{n} = 0;",
            f'  a_{n}: assert property (@(posedge clk) disable iff (!rst_n) {body}) '
            f'else $display("ASSERT_FAIL GEN:{n} t=%0t", $time);',
            f"  always @(posedge clk) if (rst_n && ({ant})) cov_{n}++;",
        ]
        ranges[n] = (start, len(lines))
    if cands:
        lines.append("  final begin")
        lines += [f'    $display("COVER_COUNT {p["name"]} %0d", cov_{p["name"]});' for p in cands]
        lines.append("  end")
    lines.append("endmodule")
    return "\n".join(lines) + "\n", ranges
